/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Config {
  images: Array<Buffer>
  size?: number
  borderMargin?: number
  margin?: number
  saveFile?: boolean
  savePath?: string
  bgFile?: string
  bgColor: Array<number>
}
export declare function generateGroupAvatar(cfg: Config): Promise<Buffer | null>
